spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.99.172.188:8848
        namespace: f4afe9a5-925e-407b-b008-15700cb65bda
  application:
    name: gulimall-coupon
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 7000

#user1:
#  name: aaa
#  age: 11
