spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.99.172.188:8848
        namespace: f4afe9a5-925e-407b-b008-15700cb65bda
    gateway:
      routes:
        - id: test_baidu.com
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_qq.com
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
  application:
    name: gulimall-gateway

server:
  port: 88